name: Build & Deploy

on:
  workflow_call:
    inputs:
      cr-host:
        required: false
        type: string
        default: "docker.io"
        description: "Container registry hostname"
      cr-login:
        required: false
        type: string
        default: "providus"
        description: "Username for container registry"
      build-context:
        required: false
        type: string
        default: "."
        description: "Build context for docker build"
      dockerfile:
        required: false
        type: string
        default: "Dockerfile"
        description: "Path to Dockerfile"
      image-name:
        required: true
        type: string
        description: "Name of the image, format quay.io/providus/tenant-service or just providus/tenant-service"
      argocd-host:
        required: true
        type: string
        description: "ArgoCD hostname"
      argocd-version:
        required: false
        type: string
        description: "ArgoCD binary version"
        default: "2.14.11"
      tenant:
        required: true
        type: string
        description: "Tenant name"
      app-name:
        required: true
        type: string
      sonar-host:
        required: false
        type: string
        default: "https://sonarqube.infra.providus.rs/"
        description: "Address of sonar scanner"
      sonar-scanner-version:
        required: false
        type: string
        description: "Version of sonar scanner"
        default: "6.2.1.4610"
      env-name:
        required: false
        type: string
        default: "dev"
        description: "Environment name"
      runner-label:
        required: false
        type: string
        default: "ubuntu-24.04"
        description: "Runner name or label where to run"
      debug:
        required: false
        type: boolean
        default: false
      test-report-path:
        required: false
        type: string
        default: "target/surefire-reports/**/TEST-*.xml"
        description: "Path to test report files"
      test-report-type:
        required: false
        type: string
        default: "java-junit"
        description: "Type of test report files"
      scan-image:
        required: false
        type: string
        description: "Enable image vulnerability scanning by selecting threshold level (e.g., HIGH or CRITICAL)"
      enable-scan:
        required: false
        type: boolean
        default: false
        description: "Enable SonarQube code scan"
    secrets:
      cr-pass:
        required: true
        description: "Registry token"
      argocd-token:
        required: true
        description: "ArgoCD token"
      sonar-token:
        required: false
        description: "Sonar token"
      snyk-token:
        required: false
        description: "Snyk token"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      cr-host: ${{ inputs.cr-host }}
      cr-login: ${{ inputs.cr-login }}
      image-name: ${{ inputs.image-name }}
      build-context: ${{ inputs.build-context }}
      dockerfile: ${{ inputs.dockerfile }}
      tenant: ${{ inputs.tenant }}
      app-name: ${{ inputs.app-name }}
      sonar-host: ${{ inputs.sonar-host }}
      sonar-scanner-version: ${{ inputs.sonar-scanner-version }}
      test-report-path: ${{ inputs.test-report-path }}
      test-report-type: ${{ inputs.test-report-type }}
      scan-image: ${{ inputs.scan-image }}
      enable-scan: ${{ inputs.enable-scan }}
  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: build
    with:
      argocd-host: ${{ inputs.argocd-host }}
      argocd-version: ${{ inputs.argocd-version }}
      tenant: ${{ inputs.tenant }}
      app-name: ${{ inputs.app-name }}
      env-name: ${{ inputs.env-name }}
      runner-label: ${{ inputs.runner-label }}
      debug: ${{ inputs.debug }}
    secrets:
      argocd-token: ${{ secrets.argocd-token }}
      sonar-token: ${{ secrets.sonar-token }}
      snyk-token: ${{ secrets.snyk-token }}
